# -*- coding: utf-8 -*-
"""Another copy of Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TLZ4guzz1qd1ynhUslEd0zWSyJRj4gP8
"""

df = pd.read_csv("/content/data (2).csv")

df.shape[0]

df.describe()

x=df['x']
y=df['y']

x=np.linspace(-50,50,100)
y=theta[0]+theta[1]*x
y

xnew=np.ones((df.shape[0],2))
xnew[:,1]=x
xnew

theta=z.dot(xnew.T).dot(y)
theta

import numpy as np
x = df['x']
y = df['y']
xnew = np.ones((df.shape[0], 2))
xnew[:, 1] = x
z = xnew.T.dot(xnew)
theta = np.linalg.inv(z).dot(xnew.T).dot(y)
print(theta)

import numpy as np
theta=np.array([0.5,0.5])
theta=theta[:,np.newaxis]
learning_rate=0.001

for in range(500):

import numpy as np
theta = np.array([0.5, 0.5])
theta = theta[:, np.newaxis]
learning_rate = 0.001
n_sample = X.shape[0]

for i in range(500):
    y_pred = X.dot(theta)
    E = Y - y_pred
    grad = X.T.dot(E)
    grad_theta = (1 / n_sample) * grad
    theta = theta + learning_rate * grad_theta

import matplotlib.pyplot as plt
df = pd.read_csv("/content/data (2).csv")  # Ensure data.csv is in the same folder

# Plot the data
plt.scatter(df['x'], df['y'], color='blue', label='Data points')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Scatter Plot of data.csv')
plt.legend()
plt.grid(True)
plt.show()
print(df.plot())

import matplotlib.pyplot as plt
df = pd.read_csv("/content/noisy_data.csv")  # Ensure data.csv is in the same folder


print(df.describe())
print(df.info())
print(df.plot())

import matplotlib.pyplot as plt
df = pd.read_csv("/content/noisy_data.csv")
x=df['x']
y=df['y']
theta=z.dot(xnew.T).dot(y)
theta

xnew=np.ones((df.shape[0],2))
xnew[:,1]=x
xnew

xnew=np.ones((df.shape[0],2))
xnew[:,1]=y
xnew



theta= np.array([0.5, 0.5])
theta.shape

theta = theta[:, np.newaxis]
theta.shape

y_pred= B.dot(theta)

y=df['y'].values.reshape(-1,1)

np.sum(y_pred - y)

n_samples,n_features=df.shape[0],df.shape[1]

grad_theta=(1/n_samples)*np.dot(B.T,(y_pred - y))

grad_theta



# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from pandas.core.common import random_state
from sklearn.linear_model import LinearRegression

# Get dataset
df_sal = pd.read_csv('/content/noisy_data.csv')
df_sal.head()

# Describe data
df_sal.describe()

# Data distribution
plt.title('Y Distribution Plot')
sns.distplot(df_sal['y'])
plt.show()

# Splitting variables
X = df_sal.iloc[:, :1]  # independent
y = df_sal.iloc[:, 1:]

# Splitting dataset into test/train
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Regressor model
regressor = LinearRegression()
regressor.fit(X_train, y_train)

# Prediction result
y_pred_test = regressor.predict(X_test)     # predicted value of y_test
y_pred_train = regressor.predict(X_train)   # predicted value of y_train

plt.scatter(X_train, y_train, color = 'lightcoral')
plt.plot(X_train, y_pred_train, color = 'firebrick')
plt.title('Salary vs Experience (Training Set)')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.legend(['X_train/Pred(y_test)', 'X_train/y_train'], title = 'Sal/Exp', loc='best', facecolor='white')
plt.box(False)
plt.show()



