# -*- coding: utf-8 -*-
"""k means clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nNRFxl0QGdn9T4M_dUjo1ZlBHKBD2r1s
"""

# Importing required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs


X, y = make_blobs(n_samples=300, centers=4, cluster_std=0.60, random_state=0)

plt.scatter(X[:,0], X[:,1], s=30)
plt.title("Sample Data Before Clustering")
plt.show()


kmeans = KMeans(n_clusters=4, random_state=0, n_init=10)
kmeans.fit(X)

centers = kmeans.cluster_centers_
labels = kmeans.labels_

plt.figure(figsize=(8,6))
sns.scatterplot(x=X[:,0], y=X[:,1], hue=labels, palette="Set1", s=50, alpha=0.8)
plt.scatter(centers[:,0], centers[:,1], c='black', s=200, marker='X', label="Centroids")
plt.title("K-Means Clustering Result")
plt.legend()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# Step 1: Create sample dataset (2D points)
X = np.array([
    [1, 2], [1.5, 1.8], [5, 8],
    [8, 8], [1, 0.6], [9, 11],
    [8, 2], [10, 2], [9, 3]
])

# Number of clusters
k = 3

# Step 2: Initialize centroids randomly
np.random.seed(0)
centroids = X[np.random.choice(X.shape[0], k, replace=False)]

# Function to calculate distance
def euclidean_distance(a, b):
    return np.sqrt(np.sum((a - b) ** 2))

# Step 3: Run iterations
for _ in range(10):  # fixed number of iterations
    clusters = [[] for _ in range(k)]

    # Assign each point to the nearest centroid
    for point in X:
        distances = [euclidean_distance(point, c) for c in centroids]
        cluster_index = np.argmin(distances)
        clusters[cluster_index].append(point)

    # Update centroids (mean of points in cluster)
    new_centroids = []
    for cluster in clusters:
        new_centroids.append(np.mean(cluster, axis=0))
    centroids = np.array(new_centroids)

# Final clusters
clusters = [[] for _ in range(k)]
for point in X:
    distances = [euclidean_distance(point, c) for c in centroids]
    cluster_index = np.argmin(distances)
    clusters[cluster_index].append(point)

# Step 4: Visualization
colors = ['r', 'g', 'b']
for cluster_index, cluster in enumerate(clusters):
    cluster = np.array(cluster)
    plt.scatter(cluster[:, 0], cluster[:, 1], color=colors[cluster_index], s=100)

# Plot centroids
plt.scatter(centroids[:, 0], centroids[:, 1], color='black', marker='X', s=200, label="Centroids")
plt.title("K-Means Clustering (Without Library)")
plt.legend()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# Step 1: Create sample dataset (2D points)
X = np.array([
    [1, 2], [1.5, 1.8], [5, 8],
    [8, 8], [1, 0.6], [9, 11],
    [8, 2], [10, 2], [9, 3]
])

# Number of clusters
k = 3

# Step 2: Initialize centroids randomly
np.random.seed(0)
centroids = X[np.random.choice(X.shape[0], k, replace=False)]

# Function to calculate distance
def euclidean_distance(a, b):
    return np.sqrt(np.sum((a - b) ** 2))

# Step 3: Run iterations
for _ in range(10):  # fixed number of iterations
    clusters = [[] for _ in range(k)]

    # Assign each point to the nearest centroid
    for point in X:
        distances = [euclidean_distance(point, c) for c in centroids]
        cluster_index = np.argmin(distances)
        clusters[cluster_index].append(point)

    # Update centroids (mean of points in cluster)
    new_centroids = []
    for cluster in clusters:
        new_centroids.append(np.mean(cluster, axis=0))
    centroids = np.array(new_centroids)

# Final clusters
clusters = [[] for _ in range(k)]
for point in X:
    distances = [euclidean_distance(point, c) for c in centroids]
    cluster_index = np.argmin(distances)
    clusters[cluster_index].append(point)

# Step 4: Visualization
colors = ['r', 'g', 'b']
for cluster_index, cluster in enumerate(clusters):
    cluster = np.array(cluster)
    plt.scatter(cluster[:, 0], cluster[:, 1], color=colors[cluster_index], s=100)

# Plot centroids
plt.scatter(centroids[:, 0], centroids[:, 1], color='black', marker='X', s=200, label="Centroids")
plt.title("K-Means Clustering (Without Library)")
plt.legend()
plt.show()