# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V_I72uNQTZ4sdG9UngqPkSut48MEphbf
"""

!pip install numpy

import numpy as np


def step_function(x):
    return np.where(x >= 0, 1, 0)


X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])
y = np.array([0, 0, 0, 1])


np.random.seed(42)
weights = np.random.rand(2)
bias = np.random.rand(1)


learning_rate = 0.1
epochs = 10


for epoch in range(epochs):
    for i in range(len(X)):
        z = np.dot(X[i], weights) + bias
        y_pred = step_function(z)


        error = y[i] - y_pred
        weights += learning_rate * error * X[i]
        bias += learning_rate * error

    print(f"Epoch {epoch+1}, Weights: {weights}, Bias: {bias}")

print("\nTesting:")
for x in X:
    z = np.dot(x, weights) + bias
    print(f"Input: {x}, Output: {step_function(z)[0]}")

import numpy as np

x1=[1,1,1,1]
x2=[1,0,1,0]


def activation(x):
    if (x >= 0):
      return 1
    else:
      return 0

w0={0.5}
w1={0.85}
w2={0.4}
for w in epoch:
  for x,y in zip(x,y):
    sum = x[0]*w0 + x[1]*w1 + x[2]*w2

y^=activation(x)

w= w0 + (y-y^i)* x

import numpy as np

x1 = [1, 1, 1, 1]
x2 = [1, 0, 1, 0]
x3 = [1, 1, 0, 0]


X = np.array([[x1[i], x2[i], x3[i]] for i in range(4)])


y = np.array([1, 1, 1, 0])

def activation(x):
    return 1 if x >= 0 else 0


w = np.array([0.5, 0.85, 0.4])
learning_rate = 0.1
epochs = 20

for epoch in range(epochs):
    print(f"Epoch {epoch + 1}")
    for i in range(len(X)):
        x_i = X[i]
        y_true = y[i]

        weighted_sum = np.dot(x_i, w)
        y_pred = activation(weighted_sum)

        error = y_true - y_pred


        w = w + learning_rate * error * x_i
        print(f"Input: {x_i}, Prediction: {y_pred}, True: {y_true}, Updated Weights: {w}")

print("\nFinal weights:", w)